---

test_name: Certificando que o servidor dobre o número corretamente

stages:
  - name: Certifique-se de que o número foi retornado corretamente
    request:
      url: http://localhost:5000/double
      json:
        number: 5
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        double: 10

---

test_name: Verifica como inputs inválidos são lidados

stages:
  - name: Certifique-se que números inválidos não causem erro
    request:
      url: http://localhost:5000/double
      json:
        number: dkfsd
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 400
      json:
        error: a number was not passed

  - name: Certifique-se que retorne um erro se um número não for passado 
    request:
      url: http://localhost:5000/double
      json:
        wrong_key: 5
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 400
      json:
        error: no number passed

---

test_name: Lidando com números negativos corretamente

stages:
  - name: Tendo certeza que dobre número negativo
    request:
      url: http://localhost:5000/double
      json:
        number: -5
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        double: -10


--- 

test_name: Lidando com zero corretamente

stages:
  - name: Tendo certeza que dobre o zero
    request:
      url: http://localhost:5000/double
      json:
        number: 0
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 200
      json:
        double: 0
